/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzaria;

/**
 *
 * @author ronaldoniz
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t2rdFormaPizza = new javax.swing.ButtonGroup();
        t2rdQtdeSabores = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        t3rdTipoPizza = new javax.swing.ButtonGroup();
        telaInicio = new javax.swing.JTabbedPane();
        pnlCadastrar = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        t1tblClientes = new javax.swing.JTable();
        t1btnCadastrar = new javax.swing.JButton();
        t1btnAtualizar = new javax.swing.JButton();
        t1btnBuscar = new javax.swing.JButton();
        t1btnExcluir = new javax.swing.JButton();
        t1lblID = new javax.swing.JLabel();
        t1cmpID = new javax.swing.JTextField();
        t1lblNome = new javax.swing.JLabel();
        t1lblSobrenome = new javax.swing.JLabel();
        t1lblTelefone = new javax.swing.JLabel();
        t1cmpNome = new javax.swing.JTextField();
        t1cmpSobrenome = new javax.swing.JTextField();
        t1cmpTelefone = new javax.swing.JTextField();
        pnlPedido = new javax.swing.JPanel();
        t2lblTelefone = new javax.swing.JLabel();
        t2cmpTelefone = new javax.swing.JTextField();
        t2btnBuscar = new javax.swing.JButton();
        t2lblNome = new javax.swing.JLabel();
        t2cmpNome = new javax.swing.JTextField();
        t2cmpSobrenome = new javax.swing.JTextField();
        t2btnCadastrar = new javax.swing.JButton();
        t2btnAtualizar = new javax.swing.JButton();
        t2pnlPedido = new javax.swing.JPanel();
        t2rdCircular = new javax.swing.JRadioButton();
        t2rdQuadrada = new javax.swing.JRadioButton();
        t2rdTriangular = new javax.swing.JRadioButton();
        t2lblDimensao = new javax.swing.JLabel();
        t2cmpDimensao = new javax.swing.JTextField();
        t2btnInfo = new javax.swing.JButton();
        t2lblTamanho = new javax.swing.JLabel();
        t2cmpTamanho = new javax.swing.JTextField();
        t2lblCM2 = new javax.swing.JLabel();
        t2rdSabor1 = new javax.swing.JRadioButton();
        t2rdSabor2 = new javax.swing.JRadioButton();
        t2cmbSabores1 = new javax.swing.JComboBox<String>();
        t2cmbSabores2 = new javax.swing.JComboBox<String>();
        t2lblValor = new javax.swing.JLabel();
        t2cmpvalorPizza = new javax.swing.JFormattedTextField();
        t2lblCM1 = new javax.swing.JLabel();
        t2btnIncluir = new javax.swing.JButton();
        t2cmpQtdeSabor1 = new javax.swing.JTextField();
        t2cmpQtdeSabor2 = new javax.swing.JTextField();
        t2btnInfo1 = new javax.swing.JButton();
        t2btnNovoPedido = new javax.swing.JButton();
        t2lblPedidos = new javax.swing.JLabel();
        t2cmbPedidos = new javax.swing.JComboBox<String>();
        t2lblID = new javax.swing.JLabel();
        t2cmpID = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        t2tblPedido = new javax.swing.JTable();
        t2btnEditar = new javax.swing.JButton();
        t2lblTotal = new javax.swing.JLabel();
        t2cmpValorTotal = new javax.swing.JFormattedTextField();
        t2btnSalvar = new javax.swing.JButton();
        pnlPizzas = new javax.swing.JPanel();
        t3lblID = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        pnlPrecos = new javax.swing.JPanel();
        pnlStatus = new javax.swing.JPanel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PIZZARIA");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 768));

        t1tblClientes.setRowSelectionAllowed(true);
        t1tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "SOBRENOME", "TELEFONE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        t1tblClientes.setColumnSelectionAllowed(true);
        t1tblClientes.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(t1tblClientes);
        t1tblClientes.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (t1tblClientes.getColumnModel().getColumnCount() > 0) {
            t1tblClientes.getColumnModel().getColumn(0).setResizable(false);
            t1tblClientes.getColumnModel().getColumn(1).setResizable(false);
            t1tblClientes.getColumnModel().getColumn(2).setResizable(false);
            t1tblClientes.getColumnModel().getColumn(3).setResizable(false);
        }

        t1btnCadastrar.setText("CADASTRAR");
        t1btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1btnCadastrarActionPerformed(evt);
            }
        });

        t1btnAtualizar.setText("ATUALIZAR");
        t1btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1btnAtualizarActionPerformed(evt);
            }
        });

        t1btnBuscar.setText("BUSCAR");
        t1btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1btnBuscarActionPerformed(evt);
            }
        });

        t1btnExcluir.setText("EXCLUIR");
        t1btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1btnExcluirActionPerformed(evt);
            }
        });

        t1lblID.setText("ID:");

        t1cmpID.setEditable(false);
        t1cmpID.setMaximumSize(new java.awt.Dimension(6, 20));

        t1lblNome.setText("Nome:");

        t1lblSobrenome.setText("Sobrenome:");

        t1lblTelefone.setText("Telefone:");

        t1cmpNome.setMaximumSize(new java.awt.Dimension(25, 20));
        t1cmpNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1cmpNomeActionPerformed(evt);
            }
        });

        t1cmpSobrenome.setMaximumSize(new java.awt.Dimension(30, 20));
        t1cmpSobrenome.setPreferredSize(new java.awt.Dimension(30, 20));

        javax.swing.GroupLayout pnlCadastrarLayout = new javax.swing.GroupLayout(pnlCadastrar);
        pnlCadastrar.setLayout(pnlCadastrarLayout);
        pnlCadastrarLayout.setHorizontalGroup(
            pnlCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(pnlCadastrarLayout.createSequentialGroup()
                        .addGroup(pnlCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCadastrarLayout.createSequentialGroup()
                                .addGroup(pnlCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t1lblID)
                                    .addComponent(t1cmpID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t1cmpNome, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t1lblNome)))
                            .addGroup(pnlCadastrarLayout.createSequentialGroup()
                                .addComponent(t1btnAtualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(t1btnExcluir)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t1cmpSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t1lblSobrenome))
                        .addGap(15, 15, 15)
                        .addGroup(pnlCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t1lblTelefone)
                            .addComponent(t1cmpTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlCadastrarLayout.createSequentialGroup()
                        .addComponent(t1btnCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(t1btnBuscar)))
                .addContainerGap())
        );
        pnlCadastrarLayout.setVerticalGroup(
            pnlCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastrarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t1lblID)
                    .addComponent(t1lblTelefone)
                    .addComponent(t1lblSobrenome)
                    .addComponent(t1lblNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t1cmpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t1cmpNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t1cmpSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t1cmpTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t1btnBuscar)
                    .addComponent(t1btnCadastrar))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t1btnExcluir)
                    .addComponent(t1btnAtualizar))
                .addGap(7, 7, 7))
        );

        telaInicio.addTab("CADASTRAR CLIENTES", pnlCadastrar);

        t2lblTelefone.setText("Telefone:");

        t2btnBuscar.setText("BUSCAR >>");

        t2lblNome.setText("Cliente:");

        t2btnCadastrar.setText("CADASTRAR");

        t2btnAtualizar.setText("ATUALIZAR");

        t2pnlPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        t2rdFormaPizza.add(t2rdCircular);
        t2rdCircular.setText("Circular");

        t2rdFormaPizza.add(t2rdQuadrada);
        t2rdQuadrada.setText("Quadrada");

        t2rdFormaPizza.add(t2rdTriangular);
        t2rdTriangular.setText("Triangular");
        t2rdTriangular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2rdTriangularActionPerformed(evt);
            }
        });

        t2lblDimensao.setText("Dimensão: ");

        t2btnInfo.setText("?");
        t2btnInfo.setToolTipText("<html>\nCircular: Min 7 Max 23<br>\nQuadrada: Min 10 Max 40<br>\nTriangular: Min 20 Max 60<br>\n</html>");

        t2lblTamanho.setText("Tamanho:");

        t2cmpTamanho.setToolTipText("");

        t2lblCM2.setText("cm²");

        t2rdQtdeSabores.add(t2rdSabor1);
        t2rdSabor1.setSelected(true);
        t2rdSabor1.setText("1 Sabor");
        t2rdSabor1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t2rdSabor1MouseClicked(evt);
            }
        });

        t2rdQtdeSabores.add(t2rdSabor2);
        t2rdSabor2.setText("2 Sabores");
        t2rdSabor2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t2rdSabor2MouseClicked(evt);
            }
        });

        t2cmbSabores1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        t2cmbSabores1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2cmbSabores1ActionPerformed(evt);
            }
        });

        t2cmbSabores2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        t2cmbSabores2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2cmbSabores2ActionPerformed(evt);
            }
        });

        t2lblValor.setText("VALOR DA PIZZA");

        t2cmpvalorPizza.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));

        t2lblCM1.setText("cm");

        t2btnIncluir.setText("INCLUIR NO PEDIDO");

        t2btnInfo1.setText("?");
        t2btnInfo1.setToolTipText("100cm² a 1600cm²");

        javax.swing.GroupLayout t2pnlPedidoLayout = new javax.swing.GroupLayout(t2pnlPedido);
        t2pnlPedido.setLayout(t2pnlPedidoLayout);
        t2pnlPedidoLayout.setHorizontalGroup(
            t2pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(t2pnlPedidoLayout.createSequentialGroup()
                .addGroup(t2pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(t2pnlPedidoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(t2pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t2lblValor)
                            .addGroup(t2pnlPedidoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(t2cmpvalorPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(t2btnIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2))
                    .addGroup(t2pnlPedidoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(t2rdCircular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(t2rdQuadrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(t2rdTriangular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, t2pnlPedidoLayout.createSequentialGroup()
                        .addGroup(t2pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t2rdSabor1)
                            .addComponent(t2rdSabor2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(t2pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t2cmbSabores1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t2cmbSabores2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(t2pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t2cmpQtdeSabor1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t2cmpQtdeSabor2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(t2pnlPedidoLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(t2lblDimensao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t2cmpDimensao, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t2lblCM1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(t2btnInfo)
                        .addGap(18, 18, 18)
                        .addComponent(t2lblTamanho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(t2cmpTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(t2lblCM2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t2btnInfo1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        t2pnlPedidoLayout.setVerticalGroup(
            t2pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(t2pnlPedidoLayout.createSequentialGroup()
                .addGroup(t2pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(t2rdQuadrada)
                    .addComponent(t2rdCircular)
                    .addComponent(t2rdTriangular))
                .addGap(6, 6, 6)
                .addGroup(t2pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t2lblDimensao)
                    .addComponent(t2cmpDimensao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t2lblTamanho)
                    .addComponent(t2cmpTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t2lblCM2)
                    .addComponent(t2btnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t2lblCM1)
                    .addComponent(t2btnInfo1))
                .addGap(18, 18, 18)
                .addGroup(t2pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t2rdSabor1)
                    .addComponent(t2cmbSabores1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t2cmpQtdeSabor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(t2pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t2rdSabor2)
                    .addComponent(t2cmbSabores2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t2cmpQtdeSabor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(t2pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(t2pnlPedidoLayout.createSequentialGroup()
                        .addComponent(t2lblValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(t2cmpvalorPizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 7, Short.MAX_VALUE))
                    .addComponent(t2btnIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        t2cmbSabores2.setVisible(false);
        t2cmpQtdeSabor2.setVisible(false);

        t2btnNovoPedido.setText("NOVO PEDIDO");
        t2btnNovoPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t2btnNovoPedidoMouseClicked(evt);
            }
        });

        t2lblPedidos.setText("Pedidos:");

        t2cmbPedidos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        t2lblID.setText("ID:");

        t2cmpID.setEditable(false);

        t2tblPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "FORMA", "DIMENSÃO", "TAMANHO (cm²)", "SABORES", "QUANTIDADE", "VALOR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        t2tblPedido.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(t2tblPedido);
        if (t2tblPedido.getColumnModel().getColumnCount() > 0) {
            t2tblPedido.getColumnModel().getColumn(0).setResizable(false);
            t2tblPedido.getColumnModel().getColumn(1).setResizable(false);
            t2tblPedido.getColumnModel().getColumn(2).setResizable(false);
            t2tblPedido.getColumnModel().getColumn(3).setResizable(false);
            t2tblPedido.getColumnModel().getColumn(4).setResizable(false);
            t2tblPedido.getColumnModel().getColumn(5).setResizable(false);
        }

        t2btnEditar.setText("EDITAR PEDIDO");
        t2btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t2btnEditarMouseClicked(evt);
            }
        });

        t2lblTotal.setText("TOTAL PEDIDO");

        t2cmpValorTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));

        t2btnSalvar.setText("SALVAR");

        javax.swing.GroupLayout pnlPedidoLayout = new javax.swing.GroupLayout(pnlPedido);
        pnlPedido.setLayout(pnlPedidoLayout);
        pnlPedidoLayout.setHorizontalGroup(
            pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPedidoLayout.createSequentialGroup()
                        .addGroup(pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPedidoLayout.createSequentialGroup()
                                .addComponent(t2lblTelefone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(t2cmpTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(t2btnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t2btnNovoPedido))
                            .addGroup(pnlPedidoLayout.createSequentialGroup()
                                .addComponent(t2lblNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlPedidoLayout.createSequentialGroup()
                                        .addComponent(t2cmpNome, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(t2cmpSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(pnlPedidoLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(t2btnAtualizar))))
                                    .addGroup(pnlPedidoLayout.createSequentialGroup()
                                        .addComponent(t2btnCadastrar)
                                        .addGap(169, 169, 169))))
                            .addGroup(pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPedidoLayout.createSequentialGroup()
                                    .addComponent(t2lblID)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(t2cmpID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(t2btnEditar))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPedidoLayout.createSequentialGroup()
                                    .addComponent(t2lblPedidos)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(t2cmbPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t2pnlPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPedidoLayout.createSequentialGroup()
                        .addGroup(pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlPedidoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(t2btnSalvar))
                            .addGroup(pnlPedidoLayout.createSequentialGroup()
                                .addComponent(jScrollPane3)
                                .addGroup(pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlPedidoLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(t2lblTotal))
                                    .addGroup(pnlPedidoLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(t2cmpValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(28, 28, 28))))
        );
        pnlPedidoLayout.setVerticalGroup(
            pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t2pnlPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPedidoLayout.createSequentialGroup()
                        .addGroup(pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t2lblTelefone)
                            .addComponent(t2cmpTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t2btnBuscar)
                            .addComponent(t2btnNovoPedido))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t2lblNome)
                            .addComponent(t2cmpNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t2cmpSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t2btnCadastrar)
                            .addComponent(t2btnAtualizar))
                        .addGap(61, 61, 61)
                        .addGroup(pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t2lblPedidos)
                            .addComponent(t2cmbPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t2lblID)
                            .addComponent(t2cmpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t2btnEditar))))
                .addGap(18, 18, 18)
                .addGroup(pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPedidoLayout.createSequentialGroup()
                        .addComponent(t2lblTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t2cmpValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t2btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        t2pnlPedido.setVisible(false);

        telaInicio.addTab("REALIZAR PEDIDO", pnlPedido);

        t3lblID.setText("ID:");

        jTextField1.setEditable(false);

        jLabel1.setText("Nome da Pizza");

        jLabel2.setText("Tipo da Pizza");

        jButton1.setText("ADICIONAR SABOR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        t3rdTipoPizza.add(jRadioButton1);
        jRadioButton1.setText("SIMPLES");

        t3rdTipoPizza.add(jRadioButton2);
        jRadioButton2.setText("ESPECIAL");

        t3rdTipoPizza.add(jRadioButton3);
        jRadioButton3.setText("PREMIUM");

        javax.swing.GroupLayout pnlPizzasLayout = new javax.swing.GroupLayout(pnlPizzas);
        pnlPizzas.setLayout(pnlPizzasLayout);
        pnlPizzasLayout.setHorizontalGroup(
            pnlPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPizzasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPizzasLayout.createSequentialGroup()
                        .addComponent(t3lblID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPizzasLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPizzasLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton3))
                    .addComponent(jButton1))
                .addContainerGap(459, Short.MAX_VALUE))
        );
        pnlPizzasLayout.setVerticalGroup(
            pnlPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPizzasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t3lblID)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        telaInicio.addTab("CADASTRAR PIZZAS", pnlPizzas);

        javax.swing.GroupLayout pnlPrecosLayout = new javax.swing.GroupLayout(pnlPrecos);
        pnlPrecos.setLayout(pnlPrecosLayout);
        pnlPrecosLayout.setHorizontalGroup(
            pnlPrecosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
        );
        pnlPrecosLayout.setVerticalGroup(
            pnlPrecosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
        );

        telaInicio.addTab("ATUALIZAR PREÇOS", pnlPrecos);

        javax.swing.GroupLayout pnlStatusLayout = new javax.swing.GroupLayout(pnlStatus);
        pnlStatus.setLayout(pnlStatusLayout);
        pnlStatusLayout.setHorizontalGroup(
            pnlStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
        );
        pnlStatusLayout.setVerticalGroup(
            pnlStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
        );

        telaInicio.addTab("VERIFICAR STATUS DOS PEDIDOS", pnlStatus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaInicio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaInicio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1cmpNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1cmpNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1cmpNomeActionPerformed

    private void t1btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1btnCadastrarActionPerformed
  
    }//GEN-LAST:event_t1btnCadastrarActionPerformed

    private void t1btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1btnAtualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1btnAtualizarActionPerformed

    private void t1btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1btnBuscarActionPerformed

    private void t1btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1btnExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1btnExcluirActionPerformed

    private void t2rdTriangularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2rdTriangularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2rdTriangularActionPerformed

    private void t2btnNovoPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t2btnNovoPedidoMouseClicked
        t2pnlPedido.setVisible(true);
    }//GEN-LAST:event_t2btnNovoPedidoMouseClicked

    private void t2rdSabor2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t2rdSabor2MouseClicked
        t2cmbSabores1.setVisible(true);
        t2cmbSabores2.setVisible(true);
        t2cmpQtdeSabor1.setVisible(true);
        t2cmpQtdeSabor2.setVisible(true);
    }//GEN-LAST:event_t2rdSabor2MouseClicked

    private void t2cmbSabores1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2cmbSabores1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2cmbSabores1ActionPerformed

    private void t2rdSabor1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t2rdSabor1MouseClicked
        t2cmbSabores1.setVisible(true);
        t2cmpQtdeSabor1.setVisible(true);
        t2cmbSabores2.setVisible(false);
        t2cmpQtdeSabor2.setVisible(false);
    }//GEN-LAST:event_t2rdSabor1MouseClicked

    private void t2cmbSabores2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2cmbSabores2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2cmbSabores2ActionPerformed

    private void t2btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t2btnEditarMouseClicked
        t2pnlPedido.setVisible(true);
    }//GEN-LAST:event_t2btnEditarMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel pnlCadastrar;
    private javax.swing.JPanel pnlPedido;
    private javax.swing.JPanel pnlPizzas;
    private javax.swing.JPanel pnlPrecos;
    private javax.swing.JPanel pnlStatus;
    private javax.swing.JButton t1btnAtualizar;
    private javax.swing.JButton t1btnBuscar;
    private javax.swing.JButton t1btnCadastrar;
    private javax.swing.JButton t1btnExcluir;
    private javax.swing.JTextField t1cmpID;
    private javax.swing.JTextField t1cmpNome;
    private javax.swing.JTextField t1cmpSobrenome;
    private javax.swing.JTextField t1cmpTelefone;
    private javax.swing.JLabel t1lblID;
    private javax.swing.JLabel t1lblNome;
    private javax.swing.JLabel t1lblSobrenome;
    private javax.swing.JLabel t1lblTelefone;
    private javax.swing.JTable t1tblClientes;
    private javax.swing.JButton t2btnAtualizar;
    private javax.swing.JButton t2btnBuscar;
    private javax.swing.JButton t2btnCadastrar;
    private javax.swing.JButton t2btnEditar;
    private javax.swing.JButton t2btnIncluir;
    private javax.swing.JButton t2btnInfo;
    private javax.swing.JButton t2btnInfo1;
    private javax.swing.JButton t2btnNovoPedido;
    private javax.swing.JButton t2btnSalvar;
    private javax.swing.JComboBox<String> t2cmbPedidos;
    private javax.swing.JComboBox<String> t2cmbSabores1;
    private javax.swing.JComboBox<String> t2cmbSabores2;
    private javax.swing.JTextField t2cmpDimensao;
    private javax.swing.JTextField t2cmpID;
    private javax.swing.JTextField t2cmpNome;
    private javax.swing.JTextField t2cmpQtdeSabor1;
    private javax.swing.JTextField t2cmpQtdeSabor2;
    private javax.swing.JTextField t2cmpSobrenome;
    private javax.swing.JTextField t2cmpTamanho;
    private javax.swing.JTextField t2cmpTelefone;
    private javax.swing.JFormattedTextField t2cmpValorTotal;
    private javax.swing.JFormattedTextField t2cmpvalorPizza;
    private javax.swing.JLabel t2lblCM1;
    private javax.swing.JLabel t2lblCM2;
    private javax.swing.JLabel t2lblDimensao;
    private javax.swing.JLabel t2lblID;
    private javax.swing.JLabel t2lblNome;
    private javax.swing.JLabel t2lblPedidos;
    private javax.swing.JLabel t2lblTamanho;
    private javax.swing.JLabel t2lblTelefone;
    private javax.swing.JLabel t2lblTotal;
    private javax.swing.JLabel t2lblValor;
    private javax.swing.JPanel t2pnlPedido;
    private javax.swing.JRadioButton t2rdCircular;
    private javax.swing.ButtonGroup t2rdFormaPizza;
    private javax.swing.ButtonGroup t2rdQtdeSabores;
    private javax.swing.JRadioButton t2rdQuadrada;
    private javax.swing.JRadioButton t2rdSabor1;
    private javax.swing.JRadioButton t2rdSabor2;
    private javax.swing.JRadioButton t2rdTriangular;
    private javax.swing.JTable t2tblPedido;
    private javax.swing.JLabel t3lblID;
    private javax.swing.ButtonGroup t3rdTipoPizza;
    private javax.swing.JTabbedPane telaInicio;
    // End of variables declaration//GEN-END:variables
}
